config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :artists, only: [:index, :show]
  resources :labels, only: [:index, :show]
  resources :releases, only: [:index]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :releases
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :releases
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :artist
  belongs_to :label
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def create
      @artist = Artist.new(artist_params)
      @artist.save
    end

    def index
      @artists = Artist.all
    end

    def show
      @artist = Artist.find(params[:id])
    end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def create
    @label = Label.new(label_params)
    @label.save
  end

  def index
    @labels = Label.all
  end

  def show
    @label = Label.find(params[:id])
  end


  private

  def label_params
    params.require(:label).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController

    def create
    @release = Release.new(release_params)
    @release.save
  end

  def index
    @releases = Release.all
  end

  private

  def release_params
    params.require(:release).permit(:year, :title, :format, :genre, :tracklist,
      :artist, :label)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/artists/index.html.erb
<% @artists.each do |artist| %>
  <p> <%= link_to artist.name, artist_path(artist.id)%></p>
<% end %>

app/views/artists/show.html.erb
<h1>Name: <%= @artist.name %></h1>
<h2>id: <%= @artist.id %></h2>
<h2>discogs_id: <%= @artist.discogs_id %></h2>
<h2>releases:</h2>

<% @artist.releases.each do |release| %>
<p> <%= release.title %></p>
<% end %>

app/views/labels/index.html.erb
<% @labels.each do |label| %>
  <p> <%= link_to label.name, label_path(label.id)%></p>
<% end %>

app/views/labels/show.html.erb
<h1>Name: <%= @label.name %></h1>
<h2>id: <%= @label.id %></h2>
<h2>releases:</h2>

<% @label.releases.each do |release| %>
<p> <%= release.title %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThegoodygoodyDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to 'artists', artists_path %>

<%= link_to 'labels', labels_path %>

<%= link_to 'releases', releases_path %>

app/views/releases/index.html.erb
<% @releases.each do |release| %>
<h1>Release Name: <%= release.title %></h1>

    <h2>Artist: <%= link_to release.artist.name, artist_path(release.artist.id) %></h2>
    <h2>Label: <%= link_to release.label.name, label_path(release.label.id) %></h2>

    <h2>Year:<%= release.year %></h2>
    <h2>Genre:<%= release.genre %></h2>
    <h2>Descriptions:</h2>
    <% release.format.each do |description| %>
      <ul>
        <li><%= description %></li>
      </ul>
    <% end %>

  <h2>Tracklist</h2>
  <% release.tracklist.each do |song| %>
   <ul>
    <li><%= song %></li>
  </ul>
  <% end %>
<% end %>